# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: github-recommender-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-southeast-1


resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GRUsers
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
              Resource: arn:aws:dynamodb:ap-southeast-1:771863450668:table/GRUsers
        Roles:
          - Ref: IamRoleLambdaExecution

#Resource: "arn:aws:dynamodb:ap-southeast-1:771863450668:table/GRUsers"



functions:
  newUser:
    handler: handler.newUser
    events:
      - http:
          path: newUser/{username}
          method: get
          request:
            template:
              application/json: '{ "username" : "$input.params(''username'')"}'
